# _config.yml

title: Cool Hat Project
description: A report for the EGR 314 project for Team 304 in Fall 2023.
baseurl: "https://egr-314-team-304.github.io/egr-314-team-304/" # If your site is hosted at a subpath, set this to the subpath (e.g., "/subpath")

theme: jekyll-theme-midnight

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Additional Midnight Jekyll theme specific configurations can be added here
